# Generated by Django 5.2.8 on 2025-12-02 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(max_length=50, unique=True, verbose_name='Número de Inventario')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción del Equipo')),
                ('precio_adquisicion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Adquisición')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='activo', max_length=20, verbose_name='Estado del Equipo')),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
